### ISSUE TITLE
Allow installing without setting the JAVA_HOME variable

### ISSUE THREAD

**Issue by bmarwell** [battila7/jdk-via-jabba#5]
I want to use this plugin for a toolchain. So I want to keep the existing JAVA_HOME.

**Comment by battila7** [comment]
Hi!

Thanks for raising this issue!

I have the following solution in mind, that I think is flexible enough:

  * By default, the action will set the `JAVA_HOME` env var to whatever path it downloaded the JDK to.
  * You can override this environment variable to whatever you'd like.

Let me know, if that's okay for you.

**Comment by bmarwell** [comment]
Works for me!

**Comment by battila7** [comment]
Please refer to the updated [README](https://github.com/battila7/jdk-via-jabba/tree/%236-allow-installing-without-setting-the-java-home-environment-variable-test#inputs) regarding the new configuration options.

You can find examples in the [Build Master](https://github.com/battila7/jdk-via-jabba/blob/master/.github/workflows/build-master.yml#L26) workflow.

Also, as this is a non-breaking change, it is now released on the `v1` branch.

Please reopen the issue if you run into any problems!
