### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by bmarwell** [battila7/jdk-via-jabba#6]
I would like to request support for at least windows.

**Comment by battila7** [comment]
Hi!

Thanks for raising this issue! As I don't maintain Windows builds, this did not come up as an issue for me yet.

On the other hand, this is 100% doable, although I have to look into it a bit. I'll be on it today and tomorrow.

**Comment by bmarwell** [comment]
No worries. It may also take a few weeks! Thanks for this github action! :)

**Comment by battila7** [comment]
It should now run on Windows and MacOS as well: https://github.com/battila7/jdk-via-jabba/actions/runs/373256269

Also, as this is a non-breaking change, it is now released on the v1 branch.

Please reopen the issue if you run into any problems!

**Comment by no-preserve-root** [comment]
Could you create a new marketplace release of the plugin incorporating Windows support? I would appreciate replacing my self-written logic with your plugin!

**Comment by battila7** [comment]
@no-preserve-root Yes, sure! Will do it in the evening, stay tuned 🚀

**Comment by battila7** [comment]
@no-preserve-root Release [v1.2.0](https://github.com/battila7/jdk-via-jabba/releases/tag/v1.2.0) on the GitHub Marketplace with Windows support :) Thanks for commenting, I completely forgot about creating a tag and a corresponding release.
